"""ORMroom_drop_column

Revision ID: 54d1d6ca9400
Revises: 030d3ba24900
Create Date: 2026-01-28 16:58:55.411495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54d1d6ca9400"
down_revision: Union[str, None] = "030d3ba24900"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("hotel_id", sa.Integer(), nullable=False))
    op.drop_constraint("rooms_hotels_id_fkey", "rooms", type_="foreignkey")
    op.create_foreign_key(None, "rooms", "hotels", ["hotel_id"], ["id"])
    op.drop_column("rooms", "hotels_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column("hotels_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "rooms", type_="foreignkey")
    op.create_foreign_key(
        "rooms_hotels_id_fkey", "rooms", "hotels", ["hotels_id"], ["id"]
    )
    op.drop_column("rooms", "hotel_id")
    # ### end Alembic commands ###
